image: node:16.14.2

stages:
  - install
  - build
  - release

install:
    stage: install
    script:
      - pwd
      - npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm update

dev-build:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "dist"
    paths:
      - dist
    expire_in: 1 day
  except:
    - main
